### ISSUE TITLE
Node errors when starting REST API proxy

### ISSUE THREAD

**Issue by dafna1228** [JamesOsgood/mongodb-grafana#1]
Hi, I'm experiencing some issues when I start up the  REST API proxy to MongoDB with `npm run server`
Is there a specific node or npm version I should work with?

Here are some logs:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'server' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'preserver', 'server', 'postserver' ]
5 info lifecycle grafana-mongodb@0.2.0~preserver: grafana-mongodb@0.2.0
6 info lifecycle grafana-mongodb@0.2.0~server: grafana-mongodb@0.2.0
7 verbose lifecycle grafana-mongodb@0.2.0~server: unsafe-perm in lifecycle true
8 verbose lifecycle grafana-mongodb@0.2.0~server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/lib/grafana/plugins/mongodb-grafana/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
9 verbose lifecycle grafana-mongodb@0.2.0~server: CWD: /var/lib/grafana/plugins/mongodb-grafana
10 silly lifecycle grafana-mongodb@0.2.0~server: Args: [ '-c', 'node ./dist/server/mongodb-proxy.js' ]
11 silly lifecycle grafana-mongodb@0.2.0~server: Returned: code: 1  signal: null
12 info lifecycle grafana-mongodb@0.2.0~server: Failed to exec server script
13 verbose stack Error: grafana-mongodb@0.2.0 server: `node ./dist/server/mongodb-proxy.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid grafana-mongodb@0.2.0
15 verbose cwd /var/lib/grafana/plugins/mongodb-grafana
16 verbose Linux 3.13.0-125-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "server"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error grafana-mongodb@0.2.0 server: `node ./dist/server/mongodb-proxy.js`
22 error Exit status 1
23 error Failed at the grafana-mongodb@0.2.0 server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

Thanks !

**Comment by JamesOsgood** [comment]
Apologies, I was travelling for a couple of days.

There was an error in the build script. The server uses the config package and I forgot the cd dist/server in package.json.

James

**Comment by dafna1228** [comment]
Hi, Thank you James.
Do you mean that i have to run `npm run server` from dist/server? I just tried it, and got the same debug log as i posted above.
I'm attaching the errors I got in the shell, is it more helpful?

```
ubuntu@grafana:/var/lib/grafana/plugins/mongodb-grafana/dist/server$ npm run server

> grafana-mongodb@0.2.0 server /var/lib/grafana/plugins/mongodb-grafana
> node ./dist/server/mongodb-proxy.js

WARNING: No configurations found in configuration directory:/var/lib/grafana/plugins/mongodb-grafana/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/var/lib/grafana/plugins/mongodb-grafana/node_modules/config/lib/config.js:202
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "server" is not defined
    at Config.get (/var/lib/grafana/plugins/mongodb-grafana/node_modules/config/lib/config.js:202:11)
    at Object.<anonymous> (/var/lib/grafana/plugins/mongodb-grafana/dist/server/mongodb-proxy.js:142:27)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grafana-mongodb@0.2.0 server: `node ./dist/server/mongodb-proxy.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grafana-mongodb@0.2.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-03-29T14_17_22_751Z-debug.log

```
Dafna
