### ISSUE TITLE
Search and Queries are showing an empty request

### ISSUE THREAD

**Issue by itomaldonado** [JamesOsgood/mongodb-grafana#8]
*Edit: I forgot to add that I was using Grafana v5.1.0*

I followed the installation procedures and enabled logging, but here is what I am getting:

```
REQUEST: /query:
{}
TypeError: Cannot read property 'from' of undefined
    at /Users/xxx/mongodb-grafana/dist/server/mongodb-proxy.js:101:56
    at Layer.handle [as handle_request] (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
REQUEST: /search:
{}
TypeError: Cannot read property 'trim' of undefined
    at parseQuery (/Users/xxx/mongodb-grafana/dist/server/mongodb-proxy.js:171:16)
    at /Users/xxx/mongodb-grafana/dist/server/mongodb-proxy.js:29:15
    at Layer.handle [as handle_request] (/Users/xxx/git/pervacio/cgt/mongodb-grafana/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:137:13)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
    at next (/Users/xxx/mongodb-grafana/node_modules/express/lib/router/route.js:131:14)
```

It seems that the query is not being sent, here is the example query I have been working off of:

```
db.collection.aggregate([
  {
    "$match": {
      "sessionStartTime": {
        "$gte": "$from",
        "$lte": "$to"
      }
    }
  },
  {
    "$sort": {
      "sessionStartTime": 1
    }
  },
  {
    "$project": {
      "name": "sessionId",
      "value": "$sessionId",
      "ts": "$sessionStartTime",
      "_id": 0
    }
  }
])
```

**Comment by JamesOsgood** [comment]
Hi,

It's failing on this line

```
    // Parse query string in target
    substitutions = { "$from" : new Date(req.body.range.from),
                      "$to" : new Date(req.body.range.to),
                      "$dateBucketCount" : getBucketCount(req.body.range.from, req.body.range.to, req.body.intervalMs)
                     }

```
Which would indicated that req.body.range is undefined? Can you use the grafana query inspector to look at the request? Should be something like

{
  "xhrStatus": "complete",
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/15/query",
    "data": {
      "timezone": "browser",
      "panelId": 1,
      "range": {
        "from": "2018-05-23T09:54:08.148Z",
        "to": "2018-05-23T10:09:08.148Z",
        "raw": {
          "from": "now-15m",
          "to": "now"
        }
      },
      "rangeRaw": {
        "from": "now-15m",
        "to": "now"
      },
      "interval": "500ms",
      "intervalMs": 500,

**Comment by JamesOsgood** [comment]
I'll also test with 5.1.

**Comment by itomaldonado** [comment]
Perfect, will test and get back to you, one moment~

**Comment by itomaldonado** [comment]
I found my problem. For testing purposes I configured the Datasource to send request via the browser and **not** proxied by the server. CORS was not working properly so the request was not coming through properly. Not sure why this translated to empty queries though, but as soon as I switched to queries being proxied by the server, it started working properly.

Thanks for the direction~

**Comment by JamesOsgood** [comment]
Great. Glad it's working.

James
