### ISSUE TITLE
"npm run server" command is not working.

### ISSUE THREAD

**Issue by napender** [JamesOsgood/mongodb-grafana#83]

**Comment by napender** [comment]
> grafana-mongodb@0.8.1 server /var/lib/grafana/plugins/mongodb-grafana-master
> cd dist/server && node mongodb-proxy.js

/var/lib/grafana/plugins/mongodb-grafana-master/node_modules/statman-stopwatch/lib/Stopwatch.js:125
    let delta;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/lib/grafana/plugins/mongodb-grafana-master/dist/server/mongodb-proxy.js:8:17)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-112-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "server"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! grafana-mongodb@0.8.1 server: `cd dist/server && node mongodb-proxy.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grafana-mongodb@0.8.1 server script 'cd dist/server && node mongodb-proxy.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the grafana-mongodb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd dist/server && node mongodb-proxy.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs grafana-mongodb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls grafana-mongodb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/lib/grafana/plugins/mongodb-grafana-master/npm-debug.log
ubun

**Comment by bytesnz** [comment]
You might need to try a newer version of Node. This version is currently locked to Node version 6.10.0, which is not supported by grunt, but if you remove the following lines from the *package.json* file, it works with node v10

```diff
diff --git a/package.json b/package.json
index 5e63bd8..eeb182c 100644
--- a/package.json
+++ b/package.json
@@ -18,10 +18,6 @@
   "bugs": {
     "url": "https://github.com/JamesOsgood/mongodb-grafana/issues"
   },
-  "engines": {
-    "node": "6.10.0"
-  },
-  "engineStrict": true,
   "devDependencies": {
     "babel": "^6.23.0",
     "chai": "~3.5.0",
```
